### ISSUE TITLE
Books Tab Couldn't Fetch Books (Android) 

### ISSUE THREAD

**Issue by JaxzKyd** [keaganhilliard/audiobookly#5]
![Screenshot_20221117-144704.jpg](https://user-images.githubusercontent.com/39567321/202544761-1eb0a58d-cf59-4cc9-ba14-97b11b1c89ca.jpg)

Fresh install
Logged in
Closed and reopened app (to fix the series tab not fetching)

**Comment by keaganhilliard** [comment]
Do you have a large library?

**Comment by JaxzKyd** [comment]
I would say relatively small, 
47 books/749 hours

**Comment by keaganhilliard** [comment]
Interesting, do all of the other tabs work?

**Comment by JaxzKyd** [comment]
I don't have any collections, so I can't speak for that tab. But the home, authors, and series tabs all work

**Comment by keaganhilliard** [comment]
Ok so this is generally a single or multiple audiobooks with some value that can't be converted correctly (e.g. chapter duration comes back as text rather than a number). Just the nature of JavaScript api's being untyped vs Dart being typed, maybe I can try to put a button that shows what the actual error is. I'll think about the best way to do that.

**Comment by keaganhilliard** [comment]
@JaxzKyd This is potentially fixed in v0.1.2-alpha.

**Comment by JaxzKyd** [comment]
Right, I should probably close this now :P
